#!/usr/bin/env python3
"""
Core State Module
Defines the shared state schema for LangGraph agents
"""

from typing import TypedDict, List, Dict, Optional


class AeroForgeState(TypedDict):
    """
    Shared state for the aeroForge-G3 multi-agent system.

    This TypedDict defines the structure of data that flows between
    agents in the LangGraph workflow.
    """

    mission_prompt: str
    """
    User's high-level mission requirements.
    Example: "Design a high-speed drone for Mars atmosphere with 2kg payload"
    """

    cad_code: str
    """
    Current Python code for build123d CAD model.
    Generated by the Designer agent and updated on iterations.
    """

    urdf_path: str
    """
    File path to the generated URDF model.
    Created from CAD code by SceneBuilder.
    """

    simulation_metrics: Dict
    """
    Metrics and telemetry from physics simulation.
    Includes stability scores, forces, velocities, and analysis results.
    """

    errors: List[str]
    """
    List of errors encountered during the workflow.
    Includes Python syntax errors, simulation failures, etc.
    """

    iteration: int
    """
    Current iteration count (0-indexed).
    Used to prevent infinite loops.
    """

    status: str
    """
    Current workflow status.
    Values: 'initialized', 'designing', 'simulating', 'analyzing', 'complete', 'failed'
    """

    designer_feedback: Optional[str]
    """
    Feedback from the Supervisor/Physicist agent to guide the Designer.
    Provides context for iterations (e.g., "increase arm thickness").
    """

    design_history: List[str]
    """
    History of CAD code versions across iterations.
    Useful for rollback and analysis.
    """

    simulation_results: Optional[Dict]
    """
    Detailed raw simulation results from Genesis.
    Contains full telemetry time-series data.
    """


def create_initial_state(mission_prompt: str) -> AeroForgeState:
    """
    Create an initial state object from a mission prompt.

    Args:
        mission_prompt: User's mission requirements

    Returns:
        Initialized AeroForgeState dictionary
    """
    return AeroForgeState(
        mission_prompt=mission_prompt,
        cad_code="",
        urdf_path="",
        simulation_metrics={},
        errors=[],
        iteration=0,
        status="initialized",
        designer_feedback=None,
        design_history=[],
        simulation_results=None
    )
